### ISSUE TITLE
Mobile Drag Function

### ISSUE THREAD

**Issue by bfrickenstein** [asantibanez/laravel-blade-sortable#4]
Hi, 
is there a touch Drag function? On a mobile device i cant sort my Items.

**Comment by nam-co** [comment]
I think Andres prefers issues, emailed to him,  like he mentions on the readme, but this is a true issue

**Comment by asantibanez** [comment]
Hey @bfrickenstein 

It should work. I am using [SortableJS](http://sortablejs.github.io/Sortable/) under the hood and their demos seem to work on mobile.
