### ISSUE TITLE
Sort between groups, not inside

### ISSUE THREAD

**Issue by nam-co** [asantibanez/laravel-blade-sortable#5]
Hi Andres , thanks for everything, I was wondering if its possible to limit the  sorting in a group it self, for example you can drag from A to  B, but not change the positions in A itself,  appreciate any help, thanks

<img width="824" alt="Screen Shot 2021-04-02 at 2 01 00 PM" src="https://user-images.githubusercontent.com/3951529/113445923-538fcd80-93bc-11eb-8d0f-b9fe0ba7dafb.png">

Basically:
1. Allow from A to B
2. Don't allow from B to A
3. Don't allow sorting inside A
4. Allow sorting inside B

**Comment by asantibanez** [comment]
Available in the next release @nam-co 👍

**Comment by nam-co** [comment]
Gracias Andres, I think is a useful feature
